language: python

python:
  - "3.7"

jobs:
  include:
    - stage: "Build Lab 2."
      name: "Run tests for Lab 2"
      python: 3.7
      install:
        - cd ./Laboratorna2/
        - pipenv install
      script: make tests || true
    - stage: "Build Lab 3."
      name: "Run Djungo Server and test it accessibility. Fail to run and test"
      python: 3.7
      install:
        - cd ./Laboratorna3/
        - pipenv install
      script: ./scripts/travis-build.sh
    - stage: "Build Lab 4."
      name: "Build Docker images & Home task"
      services:
        - docker
      install:
        - cd ./Laboratorna4/
      script:
        - docker build -t moria12/lab4-examples:django-travis .
        - docker build -t moria12/lab4-examples:monitoring-travis --file Dockerfile.monitoring .
        - docker images
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker push moria12/lab4-examples:django-travis; docker push moria12/lab4-examples:monitoring-travis else echo "PR skip deploy"; fi
    - stage: "Build Lab 5."
      name: "Build and run Docker images via make"
      services:
        - docker
      install:
        - cd ./Laboratorna5/
        - make app
        - make tests
      script:
        - make run
        - make test-app
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - make docker-commit 
branches:
  only:
    - master
